//! Compiles every `crates/test-programs` guest program to a `wasm32-wasip2`
//! component and generates `gen.rs`: one path constant per program plus a
//! `foreach_<capability>!` completeness macro per name prefix.

use std::collections::{BTreeMap, HashSet};
use std::path::{Path, PathBuf};
use std::process::Command;
use std::{env, fs};

fn main() {
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set"));
    let manifest_dir =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set"));
    let test_programs = manifest_dir.join("../test-programs");
    println!("cargo:rerun-if-changed={}", test_programs.join("programs").display());
    println!("cargo:rerun-if-changed={}", test_programs.join("src").display());
    println!("cargo:rerun-if-changed={}", test_programs.join("Cargo.toml").display());

    let programs = programs(&test_programs.join("programs"));
    build_guests(&out_dir);

    let mut generated =
        String::from("// Generated by test-utils/build.rs from crates/test-programs.\n");
    let mut buckets: BTreeMap<String, Vec<String>> = BTreeMap::new();
    let mut deps_seen = HashSet::new();
    for program in &programs {
        // Always `debug`: the nested build below uses the dev profile
        // regardless of the outer profile.
        let artifact = out_dir.join("wasm32-wasip2/debug/examples").join(format!("{program}.wasm"));
        assert!(
            artifact.exists(),
            "no artifact for `{program}`: declare it as an [[example]] in \
             crates/test-programs/Cargo.toml"
        );

        let constant = program.to_uppercase();
        let path = artifact.to_str().expect("artifact path is UTF-8");
        generated.push_str(&format!(
            "/// Path to the compiled `{program}` guest component.\npub const {constant}: \
             &str = {path:?};\n"
        ));

        let capability = program.split('_').next().expect("program names are snake_case");
        match capability {
            "model" => {}
            other => panic!(
                "unknown capability prefix `{other}` in `{program}`: add it to the match in \
                 crates/test-utils/build.rs"
            ),
        }
        buckets.entry(capability.to_owned()).or_default().push(program.clone());

        emit_dep_info(&artifact, &mut deps_seen);
    }

    for (capability, names) in buckets {
        let arms: String = names.iter().map(|name| format!("        $mac!({name});\n")).collect();
        generated.push_str(&format!(
            "/// Invokes `$mac!` once per `{capability}_*` guest program, so a program \
             without a matching test fails to compile.\n#[macro_export]\nmacro_rules! \
             foreach_{capability} {{\n    ($mac:ident) => {{\n{arms}    }};\n}}\n"
        ));
    }

    fs::write(out_dir.join("gen.rs"), generated).expect("writing gen.rs");
}

// The guest program names: the `.rs` file stems under `programs/`.
fn programs(dir: &Path) -> Vec<String> {
    let mut names: Vec<String> = fs::read_dir(dir)
        .expect("reading crates/test-programs/programs")
        .map(|entry| entry.expect("reading directory entry").path())
        .filter(|path| path.extension().is_some_and(|extension| extension == "rs"))
        .map(|path| path.file_stem().and_then(|stem| stem.to_str()).expect("UTF-8 stem").to_owned())
        .collect();
    names.sort();
    names
}

fn build_guests(out_dir: &Path) {
    let cargo = env::var("CARGO").unwrap_or_else(|_| "cargo".to_owned());
    let status = Command::new(cargo)
        .args(["build", "--locked", "--package=test-programs", "--examples"])
        .arg("--target=wasm32-wasip2")
        // A dedicated target dir: the outer cargo holds the workspace one.
        .env("CARGO_TARGET_DIR", out_dir)
        .env("RUSTFLAGS", rustflags())
        .env_remove("CARGO_ENCODED_RUSTFLAGS")
        // When the outer command is `cargo clippy`, this wrapper would run
        // clippy-driver over the guests' wasm32 dep tree (including generated
        // bindings); the guests are a plain rustc build.
        .env_remove("RUSTC_WORKSPACE_WRAPPER")
        .status()
        .expect("running cargo build for the guest programs");
    assert!(status.success(), "guest program build failed");
}

// Propagate only warning denial to the nested build; other outer flags are
// native-target concerns that don't apply to the wasm32 guests.
fn rustflags() -> &'static str {
    match env::var("RUSTFLAGS") {
        Ok(flags) if flags.contains("-Dwarnings") || flags.contains("-D warnings") => "-Dwarnings",
        _ => "",
    }
}

// Register the guest's full dep-info (its sources plus every crate it pulls
// in, e.g. `omnia-guest`) so editing any of them rebuilds the component.
fn emit_dep_info(artifact: &Path, seen: &mut HashSet<String>) {
    let Ok(contents) = fs::read_to_string(artifact.with_extension("d")) else {
        return;
    };
    for line in contents.lines() {
        let Some((_, deps)) = line.split_once(": ") else {
            continue;
        };
        // dep-info escapes spaces in paths as `\ `.
        let mut current = String::new();
        for part in deps.split(' ') {
            if let Some(prefix) = part.strip_suffix('\\') {
                current.push_str(prefix);
                current.push(' ');
            } else if !part.is_empty() {
                current.push_str(part);
                if seen.insert(current.clone()) {
                    println!("cargo:rerun-if-changed={current}");
                }
                current.clear();
            }
        }
    }
}
