//! Compiles every `crates/test-programs` guest program to a `wasm32-wasip2`
//! component and generates `gen.rs`: one path constant per program plus a
//! `foreach_<capability>!` completeness macro per capability directory.

use std::collections::{BTreeMap, HashSet};
use std::path::{Path, PathBuf};
use std::process::Command;
use std::{env, fs};

/// Split point for the generated `[[example]]` list in `test-programs/Cargo.toml`.
const EXAMPLES_MARKER: &str =
    "# Generated by test-utils/build.rs from programs/<capability>/<scenario>.rs.\n";

fn main() {
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set"));
    let manifest_dir =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set"));
    let test_programs = manifest_dir.join("../test-programs");
    let programs_dir = test_programs.join("programs");
    println!("cargo:rerun-if-changed={}", programs_dir.display());
    println!("cargo:rerun-if-changed={}", test_programs.join("src").display());
    println!("cargo:rerun-if-changed={}", test_programs.join("Cargo.toml").display());

    let programs = programs(&programs_dir);
    sync_examples(&test_programs.join("Cargo.toml"), &programs);
    build_guests(&out_dir);

    let mut generated =
        String::from("// Generated by test-utils/build.rs from crates/test-programs.\n");
    let mut buckets: BTreeMap<String, Vec<String>> = BTreeMap::new();
    let mut deps_seen = HashSet::new();
    for program in &programs {
        // Always `debug`: the nested build below uses the dev profile
        // regardless of the outer profile.
        let artifact =
            out_dir.join("wasm32-wasip2/debug/examples").join(format!("{}.wasm", program.name));
        assert!(
            artifact.exists(),
            "no artifact for `{}`: sync `crates/test-programs/Cargo.toml` from `programs/`",
            program.name
        );

        let constant = program.name.to_uppercase();
        let path = artifact.to_str().expect("artifact path is UTF-8");
        generated.push_str(&format!(
            "/// Path to the compiled `{}` guest component.\npub const {constant}: \
             &str = {path:?};\n",
            program.name
        ));

        buckets.entry(program.capability.clone()).or_default().push(program.name.clone());
        emit_dep_info(&artifact, &mut deps_seen);
    }

    for (capability, names) in buckets {
        let arms: String = names.iter().map(|name| format!("        $mac!({name});\n")).collect();
        generated.push_str(&format!(
            "/// Invokes `$mac!` once per `{capability}` guest program, so a program \
             without a matching test fails to compile.\n#[macro_export]\nmacro_rules! \
             foreach_{capability} {{\n    ($mac:ident) => {{\n{arms}    }};\n}}\n"
        ));
    }

    fs::write(out_dir.join("gen.rs"), generated).expect("writing gen.rs");
}

/// One guest: `programs/<capability>/<scenario>.rs` → `<capability>_<scenario>`.
struct Program {
    name: String,
    capability: String,
    scenario: String,
}

fn programs(dir: &Path) -> Vec<Program> {
    let mut names = Vec::new();
    for entry in fs::read_dir(dir).expect("reading crates/test-programs/programs") {
        let entry = entry.expect("reading directory entry");
        let path = entry.path();
        let file_type = entry.file_type().expect("reading file type");
        if file_type.is_file() {
            panic!("programs/ entries must be capability directories, found `{}`", path.display());
        }
        if !file_type.is_dir() {
            continue;
        }

        let capability = entry.file_name().into_string().expect("UTF-8 capability directory");
        match capability.as_str() {
            "model" => {}
            other => panic!(
                "unknown capability directory `{other}`: add it to the match in \
                 crates/test-utils/build.rs"
            ),
        }
        println!("cargo:rerun-if-changed={}", path.display());

        for file in fs::read_dir(&path).expect("reading capability directory") {
            let file = file.expect("reading scenario entry");
            let file_path = file.path();
            let file_type = file.file_type().expect("reading scenario file type");
            if file_type.is_dir() {
                panic!("nested scenario groups are not supported: `{}`", file_path.display());
            }
            if !file_path.extension().is_some_and(|extension| extension == "rs") {
                continue;
            }
            println!("cargo:rerun-if-changed={}", file_path.display());
            let scenario = file_path
                .file_stem()
                .and_then(|stem| stem.to_str())
                .expect("UTF-8 scenario stem")
                .to_owned();
            names.push(Program {
                name: format!("{capability}_{scenario}"),
                capability: capability.clone(),
                scenario,
            });
        }
    }
    names.sort_by(|left, right| left.name.cmp(&right.name));
    names
}

/// Keep `[[example]]` stanzas in lockstep with `programs/<capability>/<scenario>.rs`
/// so adding a file is enough; the nested `--examples` build sees the new cdylib.
fn sync_examples(manifest: &Path, programs: &[Program]) {
    let current = fs::read_to_string(manifest).expect("reading test-programs/Cargo.toml");
    let Some((header, _)) = current.split_once(EXAMPLES_MARKER) else {
        panic!(
            "crates/test-programs/Cargo.toml must contain the line `{EXAMPLES_MARKER}` \
             so the generated [[example]] list can be refreshed"
        );
    };
    let mut next = String::from(header);
    next.push_str(EXAMPLES_MARKER);
    for program in programs {
        next.push_str(&format!(
            "\n[[example]]\nname = \"{}\"\npath = \"programs/{}/{}.rs\"\ncrate-type = [\"cdylib\"]\n",
            program.name, program.capability, program.scenario
        ));
    }
    if current != next {
        fs::write(manifest, next).expect("writing generated [[example]] stanzas");
    }
}

fn build_guests(out_dir: &Path) {
    let cargo = env::var("CARGO").unwrap_or_else(|_| "cargo".to_owned());
    let status = Command::new(cargo)
        .args(["build", "--locked", "--package=test-programs", "--examples"])
        .arg("--target=wasm32-wasip2")
        // A dedicated target dir: the outer cargo holds the workspace one.
        .env("CARGO_TARGET_DIR", out_dir)
        .env("RUSTFLAGS", rustflags())
        .env_remove("CARGO_ENCODED_RUSTFLAGS")
        // When the outer command is `cargo clippy`, this wrapper would run
        // clippy-driver over the guests' wasm32 dep tree (including generated
        // bindings); the guests are a plain rustc build.
        .env_remove("RUSTC_WORKSPACE_WRAPPER")
        .status()
        .expect("running cargo build for the guest programs");
    assert!(status.success(), "guest program build failed");
}

// Propagate only warning denial to the nested build; other outer flags are
// native-target concerns that don't apply to the wasm32 guests.
fn rustflags() -> &'static str {
    match env::var("RUSTFLAGS") {
        Ok(flags) if flags.contains("-Dwarnings") || flags.contains("-D warnings") => "-Dwarnings",
        _ => "",
    }
}

// Register the guest's full dep-info (its sources plus every crate it pulls
// in, e.g. `omnia-guest`) so editing any of them rebuilds the component.
fn emit_dep_info(artifact: &Path, seen: &mut HashSet<String>) {
    let Ok(contents) = fs::read_to_string(artifact.with_extension("d")) else {
        return;
    };
    for line in contents.lines() {
        let Some((_, deps)) = line.split_once(": ") else {
            continue;
        };
        // dep-info escapes spaces in paths as `\ `.
        let mut current = String::new();
        for part in deps.split(' ') {
            if let Some(prefix) = part.strip_suffix('\\') {
                current.push_str(prefix);
                current.push(' ');
            } else if !part.is_empty() {
                current.push_str(part);
                if seen.insert(current.clone()) {
                    println!("cargo:rerun-if-changed={current}");
                }
                current.clear();
            }
        }
    }
}
