[package]
name = "test-utils"
description = "Guest-component build pipeline and runtime harness for the e2e test suites"
publish = false
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
omnia.workspace = true
omnia-test = { workspace = true, features = ["host"] }

[build-dependencies]
omnia-test = { workspace = true, features = ["build"] }
