[package]
name = "omnia-otlp"
description = "OTLP exporters for the omnia WebAssembly component runtime's host telemetry"
readme = "README.md"
authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
anyhow.workspace = true
omnia-core.workspace = true
opentelemetry = { workspace = true, features = ["metrics", "trace"] }
opentelemetry-otlp = { workspace = true, features = ["grpc-tonic", "metrics", "trace"] }
opentelemetry_sdk = { workspace = true, features = ["metrics", "rt-tokio", "trace"] }
tracing.workspace = true
tracing-opentelemetry = { workspace = true, features = ["metrics"] }
