[package]
name = "omnia-cli"
description = "The `run` command-line grammar for omnia runtime binaries"
readme = "README.md"
authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[features]
# Enables the `compile` subcommand alongside `run`.
jit = []

[dependencies]
anyhow.workspace = true
clap.workspace = true
